name: Tag on Merge

on:
  pull_request:
    types:
      - closed

jobs:
  tag_on_merge:
    if: github.event.pull_request.merged == true && github.event.pull_request.base.ref == 'main'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Git
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"

      - name: Get latest tag
        id: get_latest_tag
        run: |
          tag=$(git tag --sort=-v:refname | head -n 1)
          tag=${tag:-0.0.0}
          echo "Latest tag: $tag"
          echo "tag=$tag" >> $GITHUB_OUTPUT

      - name: Bump patch version
        id: bump_tag
        run: |
          old_tag=${{ steps.get_latest_tag.outputs.tag }}
          IFS='.' read -r major minor patch <<< "$old_tag"
          patch=$((patch + 1))
          new_tag="$major.$minor.$patch"
          echo "New tag: $new_tag"
          echo "new_tag=$new_tag" >> $GITHUB_OUTPUT

      - name: Create and push new tag
        run: |
          git tag ${{ steps.bump_tag.outputs.new_tag }}
          git push origin ${{ steps.bump_tag.outputs.new_tag }}
